# ベースイメージ
FROM gcc:14.2.0

# 必要なツールのインストール
RUN apt-get update && apt-get install -y  --no-install-recommends \
    build-essential \
    cmake \
    make \
    gdb \
    git \
    valgrind \
    # qt and xwindow
    qt6-base-dev \
    qt6-tools-dev-tools \
    qt6-declarative-dev \
    qt6-svg-dev \
    qt6-wayland-dev \
    libgl1-mesa-dev \
    libx11-dev \
    libx11-xcb-dev \
    libxcb-xinerama0 \
    libxcb-xinerama0-dev \
    libxcb-randr0-dev \
    libxcb-xinput-dev \
    libglu1-mesa-dev \
    x11-apps \
    # pybind11 (and python3.11)
    python3.11 \
    python3.11-venv \
    python3.11-dev \
    python3-pip \
    pybind11-dev \
    # thunar (file manager)
    dbus \
    dbus-x11 \
    at-spi2-core \
    tumbler \
    thunar \
    # other file managers
    mc \
    ranger \
    # boost (selective)
    libboost-program-options-dev \
    # nlohmann/json
    nlohmann-json3-dev \
    # goole test
    libgtest-dev \
    # locale and sudo
    locales-all \
    sudo \
    # font
    fonts-noto-cjk \
    # fonts-noto-cjk-extra \ (optional)
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
# 必要に応じて PATH に Qt バイナリを追加
ENV PATH="/usr/lib/qt6/bin:${PATH}"
ENV QT_QPA_PLATFORM=offscreen

# Google Testをビルドしてインストール
RUN cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib

# デフォルトで python3.11 を使用
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    pip3 install --no-cache-dir --break-system-packages pipx && pipx ensurepath 
    # && echo 'export PATH=$PATH:$HOME/.local/bin' >> /home/hoge/.bashrc

# ユーザーディレクトリの PATH を適切に設定(pipxなどで利用)
ENV PATH="/home/hoge/.local/bin:${PATH}"

# ユーザー名とグループ名を一致させる
RUN groupadd -g 1000 hoge && \
    useradd -m -u 1000 -g hoge hoge && \
    echo "hoge ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# 作業ディレクトリをユーザーのホームに設定
WORKDIR /home/hoge

# 切り替え
USER hoge

# 自作実行ファイルを入れる場所とする
ENV PATH="/home/hoge/bin:$PATH"

# # 必要に応じてポートを公開（デバッグ用）
# EXPOSE 3000

# # デフォルトコマンド（デバッグ用にカスタマイズ可能）
# CMD ["bash"]



# Building 103.8s
# sudo docker build -t gcc1420qt:0.1.4 -f Dockerfile.014 .
